routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
)
from models.user import User
from models.topic import Topic
from routes import current_user
import os
import uuid


main = Blueprint('index', __name__)


@main.route("/")
def index():
    u = current_user()
    ms = Topic.all()
    return render_template("/topic/index.html", user=u, ms=ms)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        return redirect(url_for('.index'))
    else:
        session['user_id'] = u.id
        session.permanent = True
        return redirect(url_for('bp_topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        user_topics = Topic.all_current_user_topic(u.id)
        replied_topics = Topic.all_replied_topic(u.id)
        return render_template('profile.html', user=u, ms=user_topics, rs=replied_topics)


@main.route('/setting')
def setting():
    u = current_user()
    return render_template('setting.html', user=u)


@main.route('/change_setting', methods=['POST'])
def change_setting():
    form = request.form.to_dict()
    u = current_user()
    # 修改密码
    if 'old_pass' in form:
        old_pass = User.salted_password(form['old_pass'])
        if u.password == old_pass:
            new_pass = User.salted_password(form['new_pass'])
            User.update(u.id, password=new_pass)
    # 更改其它信息
    else:
        print('user_info', form)
        User.update(u.id, **form)
    return redirect(url_for('.profile'))


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file = request.files['avatar']

    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('static/avatar/', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/static/avatar/{}'.format(filename))

    return redirect(url_for('.profile'))


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


def not_found(e):
    return render_template('404.html')

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user, csrf_required, new_csrf_token
from models.topic import Topic


main = Blueprint('bp_topic', __name__)


@main.route("/")
def index():
    u = current_user()
    return render_template("/index.html", user=u)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    token = new_csrf_token()
    return render_template("topic/new.html", token=token)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.bootcss.com/github-markdown-css/2.10.0/github-markdown.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/prism/1.13.0/themes/prism.min.css" rel="stylesheet">
</head>
<body>
<!-- navbar -->
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <ul class='nav pull-right'>
                <li><a href='/'>首页</a></li>
                <li><a href='/'>论坛</a></li>
                <li><a href="{{ url_for('index.setting') }}">设置</a></li>
                <li><a href='{{ url_for('bp_topic.index')}}'>注册</a></li>
                <li><a href='{{ url_for('bp_topic.index')}}'>登录</a></li>
            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
    </div>
</div>

{% block main %}
{% endblock %}

{% block footer %}
{% endblock %}

</body>

{% block endscript %}
{% endblock %}
</html>

templates/index.html
{% extends "/base.html" %}
{% block title %}登陆{% endblock%}
{% block main %}
<form class="form-horizontal" method="post" action="{{ url_for('index.register') }}">
    <div class="control-group">
        <label class="control-label">用户名</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="username">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">密码</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="password">
        </div>
    </div>
    <div class="form-actions" method="post" action="{{ url_for('index.register') }}">
        <input type="submit" class="span-primary" value="注册">
    </div>
</form>
<form class="form-horizontal" method="post" action="{{ url_for('index.login') }}">
    <div class="control-group">
        <label class="control-label">用户名</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="username">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">密码</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="password">
        </div>
    </div>
    <div class="form-actions">
        <input type="submit" class="span-primary" value="登录">
    </div>
</form>
{% endblock%}

{% block footer %}
<div id="footer" class='fix-bottom'>
    <div id="footer_main">
        <div class="links">
            <a class="dark" href="https://github.com/HarpSun/BBS">源码地址</a>
            <p>Powerd By Flask</p>
        </div>
    </div>
</div>
{% endblock %}

templates/profile.html
{% extends "/base.html" %}
{% block title %}个人主页{% endblock%}
{% block main %}
<div id="main">
    <div id="sidebar">
        <div class='panel'>

            <div class='header'>
                <span class='col_fade'>个人信息</span>
            </div>
            <div class='inner'>
                <div class='user_card'>
                    <div>
                        <a class='user_avatar' href="{{ url_for('index.profile') }}">
                            <img src="{{ user.image }}" title="{{ user.username }}"/>
                        </a>
                        <span class='user_name'><a class='dark' href="{{ url_for('index.profile') }}">{{ user.username }}</a></span>

                        <div class="space clearfix"></div>
                        <span class="signature">
                            “
                            {{ user.signature }}
                            ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('bp_topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('.index') }}">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src="{{ user.image }}" class="user_avatar" title="{{ user.username}}">
                </div>
                <a class="dark">{{ user.username }}</a>
                <p class="col_fade">注册于 {{ user.created_time | format_time }}</p>

            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>
            {% for t in ms %}
            <div class="cell">

                <a class="user_avatar pull-left" href="{{ url_for('.profile') }}">
                    <img src="{{ user.image }}" title="{{ user.username}}">
                </a>

                <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                        {{ t.replies() | count }}
                    </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">
                        {{ t.views }}
                    </span>
                </span>

                <a class="last_time pull-right" href="{{ url_for('bp_topic.detail', id=t.id) }}">
                    <img class="user_small_avatar" src="{{ t.last_reply_user().image }}">
                    <span class="last_active_time">13 小时前</span>
                </a>

                <div class="topic_title_wrapper">

                    <a class="topic_title" href="{{ url_for('bp_topic.detail', id=t.id) }}" title="{{ t.title }}">
                        {{ t.title }}
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>
            {% for t in rs %}
            <div class="cell">

                <a class="user_avatar pull-left" href="{{ url_for('.profile') }}">
                    <img src="{{ user.image }}" title="{{ user.username }}">
                </a>

                <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                        {{ t.replies() | count }}
                    </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">
                        {{ t.views }}
                    </span>
                </span>
                <a class="last_time pull-right" href="{{ url_for('bp_topic.detail', id=t.id) }}">
                    <img class="user_small_avatar" src="{{ t.last_reply_user().image }}">
                    <span class="last_active_time">13 小时前</span>
                </a>
                <div class="topic_title_wrapper">
                    <a class="topic_title" href="{{ url_for('bp_topic.detail', id=t.id) }}" title="{{ t.title }}">
                        {{ t.title }}
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock%}

{% block footer %}
<div id="footer" class='fix-bottom'>
    <div id="footer_main">
        <div class="links">
            <a class="dark" href="https://github.com/HarpSun/BBS">源码地址</a>
            <p>Powerd By Flask</p>
        </div>
    </div>
</div>
{% endblock %}

templates/setting.html
{% extends "/base.html" %}
{% block title %}设置{% endblock%}
{% block main %}

<div id="main">
  <div id="sidebar">

  <div class="panel">

    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
  <div>
    <a class="user_avatar" href="{{ url_for('.profile') }}">
      <img src="{{ user.image }}" title="{{ user.username }}">
    </a>
    <span class="user_name"><a class="dark" href="{{ url_for('.profile') }}">{{ user.username }}</a></span>

    <div class="space clearfix"></div>
    <span class="signature">
        " {{ user.signature }} "
    </span>
  </div>
</div>
</div>
</div>


  <div class="panel">
    <div class="inner">
      <a href="{{ url_for('bp_topic.new') }}" id="create_topic_btn">
        <span class="span-success">发布话题</span>
      </a>
    </div>
  </div>

</div>


<div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="{{ url_for('.profile') }}">主页</a><span class="divider">/</span></li>
        <li class="active">设置</li>
      </ul>
    </div>
    <div class="inner">


      <form id="setting_form" class="form-horizontal" action="{{ url_for('.change_setting') }}" method="post">
        <div class="control-group">
          <label class="control-label" for="name">用户名</label>

          <div class="controls">
            <input class="input-xlarge readonly" id="name" name="username" size="30" type="text"  value="{{ user.username }}">
          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="signature">个性签名</label>

          <div class="controls">
            <textarea class="input-xlarge" id="signature" name="signature" size="30"></textarea>
          </div>
        </div>

        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
        </div>
      </form>
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">更改密码</span>
    </div>
    <div class="inner">
      <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.change_setting') }}" method="post">
        <div class="control-group">
          <label class="control-label" for="old_pass">当前密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="new_pass">新密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
          </div>
        </div>
        <input type="hidden" id="action" name="action" value="change_password">

        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
        </div>
      </form>
    </div>
  </div>
</div>
    <div class="panel">
        <div class="header">
            <span class="avatar">上传头像</span>
        </div>
        <div class="inner">
        <form method="post"
            action="{{ url_for('.avatar_add')}}"
            enctype="multipart/form-data"
        >
        <input type="file" name="avatar">
        <button type="submit">上传头像</button>
        </form>
        </div>
    </div>
</div>
{% endblock%}

{% block footer %}
<div id="footer">
    <div id="footer_main">
        <div class="links">
            <a class="dark" href="https://github.com/HarpSun/BBS">源码地址</a>
            <p>Powerd By Flask</p>
        </div>
    </div>
</div>
{% endblock %}